name: CI Workflow

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version:  '20.17.0'

    - name: Install dependencies
      run: npm install
      working-directory: ./group5-reactapp

    - name: Run tests
      run: npm test
      working-directory: ./group5-reactapp

    - name: Build project
      run: npm run build
      working-directory: ./group5-reactapp

      - name: Run linting
      run: npx eslint .

    

     
